# Generated by Django 6.0.4 on 2026-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
